---
apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    bomRepo: projects.registry.vmware.com/tkg
    compatibilityFilePath: tkg-compatibility
    discoverySources:
    - contextType: k8s
      oci:
        image: projects-stg.registry.vmware.com/tkg/packages/standalone-plugins:v0.25.4-tf_vmware.1
        name: default
    edition: tkg
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli-tkg
        name: core
    unstableVersionSelector: none
  features:
    cluster:
      custom-nameservers: "false"
      dual-stack-ipv4-primary: "false"
      dual-stack-ipv6-primary: "false"
    global:
      context-aware-cli-for-plugins: "true"
      context-target: "false"
      tkr-version-v1alpha3-beta: "false"
    management-cluster:
      aws-instance-types-exclude-arm: "true"
      custom-nameservers: "false"
      dual-stack-ipv4-primary: "false"
      dual-stack-ipv6-primary: "false"
      export-from-confirm: "true"
      import: "false"
      standalone-cluster-mode: "false"
    package:
      kctrl-package-command-tree: "false"
kind: ClientConfig
metadata:
  creationTimestamp: null
